version: '3.1'

services:
  redis-container:
    image: redis/redis-stack-server:7.2.0-v2
    ports:
      - 6379:6379
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 1s
    #   timeout: 2s
    #   retries: 10

  spring-boot:
    image: glaubermcunha/microservicetemplate:1.1.0
    depends_on:
      - redis-container
    ports:
      - 8080:8080
    environment:
      - spring.redis.host=redis-container
      - spring.redis.port=6379
      - spring.datasource.url=jdbc:postgresql://database-mensagens.cxanfineloz6.us-east-2.rds.amazonaws.com:5432/db_mensagens
      - spring.datasource.username=postgres
      - spring.datasource.password=postgres
